#!/usr/bin/env python3
"""Generate the Erbium SFDP byte image from the TRM 'XSPI SFPD' page.

Input: the text-stripped TRM page (see /tmp/erbium-docs/sfpd.txt) or the raw HTML.
Output: C source with `const uint8_t erbium_sfdp_image[]` plus a JSON side file.

The TRM lists every SFDP DWORD as a register ("Absolute Address: 0x..., Size: 0x4")
with bitfields and reset values; we simply materialise those.
"""
import re, sys, json, html

def strip_html(t):
    t = re.sub(r'<script.*?</script>|<style.*?</style>', '', t, flags=re.S)
    m = re.search(r'<div role="main".*', t, re.S)
    if m: t = m.group(0)
    t = re.sub(r'</tr>', '\n', t); t = re.sub(r'</t[dh]>', ' | ', t)
    t = re.sub(r'<[^>]+>', ' ', t); t = html.unescape(t)
    t = re.sub(r'[ \t]+', ' ', t); t = re.sub(r'\n\s*\n+', '\n', t)
    return t

def parse(text):
    # split into register sections
    secs = re.split(r'\n\s*(\S+) register\s*\n', text)
    regs = {}
    for i in range(1, len(secs), 2):
        name, body = secs[i], secs[i+1]
        m = re.search(r'Absolute Address: 0x([0-9A-Fa-f]+)', body)
        sz = re.search(r'Size: 0x([0-9A-Fa-f]+)', body)
        if not m or not sz: continue
        addr, size = int(m.group(1), 16), int(sz.group(1), 16)
        val = 0
        fields = []
        # rows: "31:0 | signature | r | 0x50444653 | — |"
        flat = re.sub(r'\s+', ' ', body)
        for row in re.finditer(r'(?<![\w:])(\d+)(?::(\d+))? \| (\S+) \| ([rwc, ]+?) \| (0x[0-9A-Fa-f]+|\d+) \|', flat):
            hi = int(row.group(1)); lo = int(row.group(2)) if row.group(2) else hi
            reset = int(row.group(5), 0)
            width = hi - lo + 1
            reset &= (1 << width) - 1
            val |= reset << lo
            fields.append((lo, hi, row.group(3), reset))
        regs[addr] = dict(name=name, size=size, value=val, fields=fields)
    return regs

def main():
    src = open(sys.argv[1], encoding='utf-8', errors='replace').read()
    if '<html' in src[:2000].lower(): src = strip_html(src)
    regs = parse(src)
    if not regs: sys.exit('no registers parsed')
    end = max(a + r['size'] for a, r in regs.items())
    img = bytearray(b'\xff' * end)
    for a, r in sorted(regs.items()):
        img[a:a + r['size']] = r['value'].to_bytes(r['size'], 'little')
    out = sys.argv[2] if len(sys.argv) > 2 else None
    lines = ['/* Generated by tools/gen_sfdp_from_trm.py from the Erbium TRM SFDP page. */',
             '/* DO NOT EDIT. Unlisted DWORDs read as 0xFF. */',
             '#include <stdint.h>', 'const uint8_t erbium_sfdp_image[] = {']
    for a in range(0, end, 16):
        chunk = img[a:a+16]
        if all(b == 0xff for b in chunk) and a not in regs:
            # keep image contiguous but note gaps only via comment every 256 bytes
            pass
        lines.append('    /* 0x%03x */ ' % a + ', '.join('0x%02x' % b for b in chunk) + ',')
    lines.append('};')
    lines.append('const unsigned erbium_sfdp_image_len = sizeof(erbium_sfdp_image);')
    c = '\n'.join(lines) + '\n'
    if out: open(out, 'w').write(c)
    else: sys.stdout.write(c)
    meta = {('0x%03x' % a): dict(name=r['name'], value='0x%08x' % r['value'],
             fields=[dict(lo=lo, hi=hi, name=n, reset=v) for lo, hi, n, v in r['fields']])
            for a, r in sorted(regs.items())}
    if out:
        json.dump(meta, open(out + '.json', 'w'), indent=1)
    sys.stderr.write('parsed %d DWORD registers, image %d bytes\n' % (len(regs), end))

if __name__ == '__main__':
    main()
